Update vendor directory to latest dcos-go
dcos/dcos-checks pull request #2
Opened 2017-05-19 17:17 UTC by amitaekbote

Make passes. 

amita@amita-desktop:~/Development/go-projects/src/github.com/dcos/dcos-checks$ make
rm -f ./dcos-checks
go build
bash -c "./script/test.sh"

*** Running 'gofmt' ... ***

*** Running 'goimports' ... ***

*** Running 'go lint' ... ***

*** Running 'go vet' ... ***

?   	github.com/dcos/dcos-checks	[no test files]
?   	github.com/dcos/dcos-checks/client	[no test files]
=== RUN   TestBinariesCheckBinaryExists
--- PASS: TestBinariesCheckBinaryExists (0.00s)
=== RUN   TestComponentCheckGetHealthURL
--- PASS: TestComponentCheckGetHealthURL (0.00s)
PASS
coverage: 31.9% of statements
ok  	github.com/dcos/dcos-checks/cmd	1.016s	coverage: 31.9% of statements

2017-05-19 17:32 UTC, collinvandyck requested changes

2017-05-19 17:32 UTC, collinvandyck commented on cmd/binaries_test.go
> +		t.Fatalf("Error running getHealthURL: %s", err)
Is this the right error message?

2017-05-19 17:32 UTC, collinvandyck commented on cmd/binaries_test.go
> +	c := &BinariesCheck{
Use `NewBinariesCheck` here instead of a struct literal.

2017-05-19 17:32 UTC, collinvandyck commented on cmd/binaries_check.go
> +	cmds := [...]string{"curl", "wget", "tar", "git", "xz", "unzip"}
This is an interesting syntax. I guess this defines an array literal instead of a slice literal?

2017-05-22 19:59 UTC, initcore0 approved these changes

2017-05-22 20:10 UTC, merged