Check for executables
dcos/dcos-checks pull request #4
Opened 2017-05-23 04:57 UTC by amitaekbote

amita@amita-desktop:~/Development/go-projects/src/github.com/dcos/dcos-checks$ ./dcos-checks 
DC/OS checks provides an easy interface to check the DC/OS components health

The checks could be executed against a signle node, or a whole cluster.

Usage:
  checks [command]

Available Commands:
  components  Check DC/OS components
  executable  Check for executable/executables required to install DC/OS

amita@amita-desktop:~/Development/go-projects/src/github.com/dcos/dcos-checks$ ./dcos-checks executable
FATA[0000] Error executing DC/OS verify existence of executables: No executable to check 
amita@amita-desktop:~/Development/go-projects/src/github.com/dcos/dcos-checks$ ./dcos-checks executable curl
amita@amita-desktop:~/Development/go-projects/src/github.com/dcos/dcos-checks$ ./dcos-checks executable clew
FATA[0000] Error executing DC/OS verify existence of executables: Choose from valid list of executables 
amita@amita-desktop:~/Development/go-projects/src/github.com/dcos/dcos-checks$

2017-05-23 13:44 UTC, collinvandyck requested changes

2017-05-23 13:44 UTC, collinvandyck commented on cmd/components_check.go
> +		RunCheck(nil, NewComponentCheck("DC/OS components health check"))
Should we be passing `context.Background()` here instead of `nil` for the context argument?

2017-05-23 13:44 UTC, collinvandyck commented on cmd/executable_check.go
> +		RunCheck(context.WithValue(context.Background(), "args", args), NewExecutableCheck("DC/OS verify existence of executables"))
Why are we using `context.WithValue` here?  Could  we just set the args as a property of `ExecutableCheck` instead?

2017-05-23 13:44 UTC, collinvandyck commented on cmd/checks.go
> +func NewExecutableCheck(name string) *ExecutableCheck {
Here and above, any reason not to have a return type of `DCOSChecker` instead of the concrete type (e.g. `*ExecutableCheck`?

2017-05-23 13:44 UTC, collinvandyck commented on cmd/executable_test.go
> +		t.Fatalf("Error running getHealthURL: %s", err)
What is the `getHealthURL` you're referring to here?

2017-05-23 13:44 UTC, collinvandyck commented on cmd/executable_test.go
> +func TestExecutableExists(t *testing.T) {
We should also have a test that tests what happens when the checker does not find a binary.

2017-05-23 17:08 UTC, darkonie commented on cmd/components_check.go
> +		RunCheck(nil, NewComponentCheck("DC/OS components health check"))
should be `context.TODO()`

2017-05-23 17:08 UTC, darkonie commented on cmd/executable_check.go
> +		RunCheck(context.WithValue(context.Background(), "args", args), NewExecutableCheck("DC/OS verify existence of executables"))
as discussed, we will set the binary name in NewExecutableCheck constructor.
we should also setup a context with a reasonable configurable timeout and pass it to RunCheck
```
ctx, cancel := context.WithTimeout(...)
```

2017-05-23 17:08 UTC, darkonie commented on cmd/executable_check.go
> +type ExecutableCheck struct {
this needs another field with a path to executable

2017-05-23 17:08 UTC, darkonie commented on cmd/executable_check.go
> +	var args = ctx.Value("args").([]string)
the executable will be available with `c.executable` or whatever name you chose.

2017-05-23 17:08 UTC, darkonie commented on cmd/executable_check.go
> +	if _, _, _, err := exec.Output(nil, args[0]); err != nil {
context should be passed to exec.Output
`exec.Output(ctx, ...`

2017-05-23 21:24 UTC, amitaekbote commented
@collinvandyck @darkonie ready for review

2017-05-23 21:41 UTC, initcore0 approved these changes

2017-05-23 23:16 UTC, collinvandyck requested changes
Looking better but still need some changes.

2017-05-23 23:16 UTC, collinvandyck commented on cmd/executable_check.go
> +	if c.Args == nil {
you can probably get rid of this nil checkc b/c down below you check for len(args) == 0

2017-05-23 23:16 UTC, collinvandyck commented on cmd/executable_test.go
> +func TestExecutableExists(t *testing.T) {
We still need a failure test.

2017-05-23 23:16 UTC, collinvandyck commented on cmd/executable_check.go
> +		return fmt.Errorf("Choose from valid list of executables")
Why don't we include the list of valid executables here that we allow? We already have that in the keys of `validExecutables`.

2017-05-24 23:00 UTC, amitaekbote commented on cmd/executable_test.go
> +func TestExecutableExists(t *testing.T) {
It is a negative test case

2017-05-24 23:58 UTC, collinvandyck commented on cmd/executable_test.go
> +func TestExecutableExists(t *testing.T) {
OK.

2017-05-24 23:58 UTC, collinvandyck approved these changes

2017-06-01 18:09 UTC, merged