Zookeeper quorum node check
dcos/dcos-checks pull request #6
Opened 2017-05-25 00:56 UTC by amitaekbote

https://dcos.io/docs/1.9/api/master-routes/
https://jira.mesosphere.com/browse/DCOS-15423

2017-05-25 01:13 UTC, collinvandyck requested changes

2017-05-25 01:13 UTC, collinvandyck commented on cmd/checks.go
> +	return &ComponentCheck{
Shouldn't this return a `ZookeeperQuorumCheck`?

2017-05-25 01:13 UTC, collinvandyck commented on cmd/zk_quorum_check.go
> +		return "", statusFailure, fmt.Errorf("Check can be run only on masters")
use `errors.New` if you don't have any text formatting going on

2017-05-25 01:13 UTC, collinvandyck commented on cmd/zk_quorum_check.go
> +func (zk *ZookeeperQuorumCheck) Run(ctx context.Context, cfg *CLIConfigFlags) (string, int, error) {
I'd recommend naming the return args here so that it's clear what the values represent.

2017-05-25 01:13 UTC, collinvandyck commented on cmd/zk_quorum_check.go
> +		return "", 0, err
Why do you return `0` here in the second return position instead of `statusUnknown` like the other early returns?

2017-05-25 01:13 UTC, collinvandyck commented on cmd/zk_quorum_check.go
> +		return "", statusUnknown, errors.Wrapf(err, "unable to execute GET %s", healthURLPrefix)
Should you use `url` here instead of `healthURLPrefix` ?

2017-05-25 01:13 UTC, collinvandyck commented on cmd/zk_quorum_check.go
> +	return zr.Response.Description, 1, errors.Wrap(nil, zr.ErrorMessage)
Might make sense to create a constant for `1` here if it does not already exist.

2017-05-25 01:13 UTC, collinvandyck commented on cmd/zk_quorum_check.go
> +	port := 0
`port` here is only used in the block defined by `if cfg.ForceTLS`.  let's move it into that block.

2017-05-25 01:13 UTC, collinvandyck commented on cmd/zk_quorum_check.go
> +	path := strings.Join([]string{"exhibitor/v1/cluster/state/", ""}, ip.String())
Why do you have `""` as the second string in the `[]string` slice literal?

2017-05-25 01:13 UTC, collinvandyck commented on cmd/zk_quorum_test.go
> +	for _, item := range []struct {
Probably want to rename `item` -> `testCase` to make it clearer to the reader.

2017-05-25 01:14 UTC, collinvandyck commented
Also, I think it would be nice if we gave a paragraph or so in the PR description that explains what's being done, and any sort of other information that would be helpful.

2017-05-25 01:25 UTC, amitaekbote commented
Work in progress label :) thanks for the comments though, I'll work on them 

Sent from my iPhone

> On May 24, 2017, at 6:14 PM, Collin Van Dyck <notifications@github.com> wrote:
> 
> Also, I think it would be nice if we gave a paragraph or so in the PR description that explains what's being done, and any sort of other information that would be helpful.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-06-01 21:10 UTC, amitaekbote commented on cmd/zk_quorum_check.go
> +	path := strings.Join([]string{"exhibitor/v1/cluster/state/", ""}, ip.String())
changed it not use strings

2017-06-01 21:10 UTC, amitaekbote commented
@collinvandyck ready for another pass

2017-06-01 21:56 UTC, collinvandyck requested changes
Looking much better, some changes requested.

2017-06-01 21:56 UTC, collinvandyck commented on cmd/zk_quorum_check.go
> +	Long:  `Zk quorum`,
The `Long` here is shorter than the `Short` 🤔

2017-06-01 21:56 UTC, collinvandyck commented on cmd/zk_quorum_check.go
> +		return "", statusFailure, err
Any reason not to wrap this err like we do with the other ones?

2017-06-01 21:56 UTC, collinvandyck commented on cmd/zk_quorum_check.go
> +	if zr.Response.State == 3 {
Should we have a constant like `const zkResponseServing = 3` to make this code more readable?

2017-06-01 21:56 UTC, collinvandyck commented on cmd/zk_quorum_test.go
> +			t.Fatalf("Expect %s. Got %s", testCase.expected, url.String())
You can just use `url` here instead of `url.String()`.  The `%s` formatting directive will call `.String()` for you.

2017-06-01 22:43 UTC, amitaekbote commented on cmd/zk_quorum_test.go
> +			t.Fatalf("Expect %s. Got %s", testCase.expected, url.String())
TIL

2017-06-01 22:44 UTC, amitaekbote commented
Addressed the comments

2017-06-01 22:47 UTC, collinvandyck approved these changes

2017-06-01 23:43 UTC, amitaekbote commented
https://github.com/dcos/dcos/pull/1608 tests passed

2017-06-02 17:37 UTC, merged